[package]
name = "beating"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beats = "0.1.3"
chrono = "0.4.24"
clap = { version = "4.2.4", features = ["derive"] }
